# Generated by Django 3.1.7 on 2021-04-02 09:55

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210402_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(books.models.Book.current_year)]),
        ),
    ]
